version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - wordpress-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - wordpress-network
  wordpress:
    depends_on:
      - db
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306      
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8080:80
    networks:
      - wordpress-network
networks:
  wordpress-network:
volumes:
  database: